oauth:
    resource: "@OauthBundle/Controller/"
    type:     annotation
    prefix:   /

symfony_zero_api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /v1/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

symfonyzero_user:
    resource: "@ApiBundle/Resources/config/userRouting.yml"
    prefix:   /v1

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"