symfony_zero_api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /v1/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc